stages:
  training:
    cmd: python -c "from src import pipeline; pipeline.stage_training()"
    deps:
      - src/pipeline/__init__.py
      - src/pipeline/training_pipeline.py
      - src/components/loading.py
      - src/components/data_ingestion.py
      - src/components/data_preprocessing.py
      - src/components/recommender.py
      - src/components/evaluation.py
      - src/utils/__init__.py
      - src/config/cols_to_drop.yaml
      - src/config/feature_bins.yaml
    params:
      - params.yaml:
          - content_based
          - user_based
          - cf
          - hybrid
          - evaluation
